### ISSUE TITLE
533-实现Concat

### ISSUE THREAD

**Issue by Cainiao-No1** [yuzai/type-challenge#14]
type Concat<T extends any[] , U extends any[]>=[...T , ...U]

Concat<readonly [1],readonly[2]>报错  类型 "readonly [1]" 为 "readonly"，不能分配给可变类型 "any[]"

type Concat<T extends readonly any[] , U extends readonly  any[]>=[...T , ...U]

**Comment by yuzai** [comment]
应该是后来新增了 readonly 的原因。我修改一下
